spring:
  config:
    activate:
      on-profile: prod
  # datasource:
  #   url: ${SPRING_DATASOURCE_URL}
  #   username: ${SPRING_DATASOURCE_USERNAME}
  #   password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 15


server.port: 8000
