spring:
  auth:
    jwt:
      secretKey: secretsecretsecretsecretsecretsecretsecretsecret
      refreshTokenExpiry: 36000000
      accessTokenExpiry: 36000000
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server.port: 8000
spring.redirectUri: "localhost:3000/login/kakao"