spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE}
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 15


server.port: 8000