spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 15


---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${STOP_EMAIL}
    password: ${STOP_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          debug: true
          auth: true
          timeout: 5000
          starttls:
            enable: true
    adminEmail: ${ADMIN_EMAIL}
---
minio:
  url: ${MINIO_URL}
  access:
    key: scg
  secret:
    key: ${MINIO_SECRET}
  bucket:
    name: ${MINIO_BUCKET}
---
spring:
  notion:
    secretKey: ${NOTION_SECRET}
    version: 2022-06-28
    databaseId:
      model: ddb99b6c5cc342f28dc6b8659e1b3e75
      dataset: 18cdf27cfdd84f36b28d53ebe0d88852
      jobInfo: c4f8d9c49a14422ebe4df9a9da39d826
---
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH_CLIENT_ID}
            client-name: kakao-login
            client-authentication-method: client_secret_post
            redirect-uri: ${OAUTH_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
server.port: 8000