spring:
  auth:
    jwt:
      secretKey: secretsecretsecretsecretsecretsecretsecretsecret
      refreshTokenExpiry: 36000000
      accessTokenExpiry: 36000000
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 300MB
server.port: 8000
spring.redirectUri: ${WEB_REDIRECT_URI}
