== 이벤트 공지 사항 API
:source-highlighter: highlightjs

=== 이벤트 공지 사항 생성 (POST /eventNotices)

====
operation::event-notice-controller-test/create-event-notice[snippets="http-request,request-fields,http-response,response-fields"]
====

=== 이벤트 공지 사항 리스트 조회 (GET /eventNotices)

====
operation::event-notice-controller-test/get-event-notice-list[snippets="query-parameters,http-request,http-response,response-fields"]
====

=== 이벤트 공지 사항 조회 (GET /eventNotices/{eventNoticeId})

====
operation::event-notice-controller-test/get-event-notice[snippets="path-parameters,http-request,http-response,response-fields"]
====

=== 이벤트 공지 사항 수정 (PUT /eventNotices/{eventNoticeId})

====
operation::event-notice-controller-test/update-event-notice[snippets="path-parameters,http-request,request-fields,http-response,response-fields"]
====

=== 이벤트 공지 사항 삭제 (DELETE /eventNotices/{eventNoticeId})

====
operation::event-notice-controller-test/delete-event-notice[snippets="path-parameters,http-request,http-response"]
====
