== 프로젝트 API
:source-highlighter: highlightjs

---
=== 프로젝트 조회 (GET /projects)
==== 200 OK
====
operation::project-controller-test/get-projects[snippets="http-request,http-response,query-parameters,response-fields"]
====

=== 프로젝트 생성 (POST /projects)
==== 201 Created
====
operation::project-controller-test/create-project[snippets="http-request,http-response,request-fields,response-fields"]
====

=== 프로젝트 조회 (GET /projects/{projectId})
==== 200 OK
====
operation::project-controller-test/get-project[snippets="http-request,http-response,path-parameters,response-fields"]
====

=== 프로젝트 수정 (PUT /projects/{projectId})
==== 200 OK
====
operation::project-controller-test/update-project[snippets="http-request,http-response,path-parameters,request-fields,response-fields"]
====

=== 프로젝트 삭제 (DELETE /projects/{projectId})
==== 204 No Content
====
operation::project-controller-test/delete-project[snippets="http-request,http-response,path-parameters"]
====

=== 관심 프로젝트 등록 (POST /projects/{projectId}/favorite)
==== 201 Created
====
operation::project-controller-test/create-project-favorite[snippets="http-request,http-response,path-parameters"]
====

=== 관심 프로젝트 삭제 (DELETE /projects/{projectId}/favorite)
==== 204 No Content
====
operation::project-controller-test/delete-project-favorite[snippets="http-request,http-response,path-parameters"]
====

=== 프로젝트 좋아요 등록 (POST /projects/{projectId}/like)
==== 201 Created
====
operation::project-controller-test/create-project-like[snippets="http-request,http-response,path-parameters"]
====

=== 프로젝트 좋아요 삭제 (DELETE /projects/{projectId}/like)
==== 204 No Content
====
operation::project-controller-test/delete-project-like[snippets="http-request,http-response,path-parameters"]
====

=== 프로젝트 댓글 등록 (POST /projects/{projectId}/comment)
==== 201 Created
====
operation::project-controller-test/create-project-comment[snippets="http-request,http-response,path-parameters,request-fields,response-fields"]
====

=== 프로젝트 댓글 삭제 (DELETE /projects/{projectId}/comment)
==== 204 No Content
====
operation::project-controller-test/delete-project-comment[snippets="http-request,http-response,path-parameters"]
====

=== 수상 프로젝트 조회 (GET /projects/award?year={year})
==== 200 No Content
====
operation::project-controller-test/get-award-projects[snippets="http-request,http-response,query-parameters,response-fields"]
====