== 프로젝트 API
:source-highlighter: highlightjs

---
=== 프로젝트 조회 (GET /projects)

====
operation::project-controller-test/get-projects[snippets="http-request,http-response,query-parameters,response-fields"]
====

=== 프로젝트 생성 (POST /projects)

====
operation::project-controller-test/create-project[snippets="http-request,http-response,request-fields,response-fields"]
====

=== 프로젝트 엑셀 일괄등록 (POST /projects/excel)

====
operation::project-excel-controller-test/create-project-excel[snippets="http-request,http-response,response-fields"]
====

=== 프로젝트 조회 (GET /projects/{projectId})

====
operation::project-controller-test/get-project[snippets="http-request,http-response,path-parameters,response-fields"]
====

=== 프로젝트 수정 (PUT /projects/{projectId})

====
operation::project-controller-test/update-project[snippets="http-request,http-response,path-parameters,request-fields,response-fields"]
====

=== 프로젝트 삭제 (DELETE /projects/{projectId})

====
operation::project-controller-test/delete-project[snippets="http-request,http-response,path-parameters"]
====

=== 관심 프로젝트 등록 (POST /projects/{projectId}/favorite)

====
operation::project-controller-test/create-project-favorite[snippets="http-request,http-response,path-parameters"]
====

=== 관심 프로젝트 삭제 (DELETE /projects/{projectId}/favorite)

====
operation::project-controller-test/delete-project-favorite[snippets="http-request,http-response,path-parameters"]
====

=== 프로젝트 좋아요 등록 (POST /projects/{projectId}/like)

====
operation::project-controller-test/create-project-like[snippets="http-request,http-response,path-parameters"]
====

=== 프로젝트 좋아요 삭제 (DELETE /projects/{projectId}/like)

====
operation::project-controller-test/delete-project-like[snippets="http-request,http-response,path-parameters"]
====

=== 프로젝트 댓글 등록 (POST /projects/{projectId}/comment)

====
operation::project-controller-test/create-project-comment[snippets="http-request,http-response,path-parameters,request-fields,response-fields"]
====

=== 프로젝트 댓글 삭제 (DELETE /projects/{projectId}/comment)

====
operation::project-controller-test/delete-project-comment[snippets="http-request,http-response,path-parameters"]
====

=== 수상 프로젝트 조회 (GET /projects/award?year={year})

====
operation::project-controller-test/get-award-projects[snippets="http-request,http-response,query-parameters,response-fields"]
====
