== 대담 영상 API
:source-highlighter: highlightjs

---
=== 대담 영상 생성 (POST /talks)
====
operation::talk-controller-test/create-talk[snippets="http-request,request-fields,http-response,response-fields"]
====

---
=== 대담 영상 리스트 조회 (GET /talks)
====
operation::talk-controller-test/get-talk-list[snippets="http-request,query-parameters,http-response,response-fields"]
====

---
=== 대담 영상 단건 조회 (GET /talks/{talkId})
====
operation::talk-controller-test/get-talk[snippets="http-request,path-parameters,http-response,response-fields"]
====

---
=== 대담 영상 수정 (PUT /talks/{talkId})
====
operation::talk-controller-test/update-talk[snippets="http-request,path-parameters,request-fields,http-response,response-fields"]
====

---
=== 대담 영상 삭제 (DELETE /talks/{talkId})
====
operation::talk-controller-test/delete-talk[snippets="http-request,path-parameters,http-response"]
====

---
=== 대담 영상의 퀴즈 조회 (GET /talks/{talkId}/quiz)
====
operation::talk-controller-test/get-quiz[snippets=http-request,path-parameters,http-response,response-fields"]
====

---
=== 대담 영상의 퀴즈 결과 제출 (POST /talks/{talkId}/quiz)
====
operation::talk-controller-test/submit-quiz[snippets="http-request,path-parameters,request-fields,http-response,response-fields"]
====
