== 유저 API
:source-highlighter: highlightjs

---

=== 로그인 유저 기본 정보 조회 (GET /users/me)
====
operation::user-controller-test/get-me[snippets="http-request,http-response,response-fields"]
====

=== 로그인 유저 기본 정보 수정 (PUT /users/me)
====
operation::user-controller-test/update-me[snippets="http-request,request-fields,http-response,response-fields"]
====

=== 유저 탈퇴 (DELETE /users/me)
====
operation::user-controller-test/delete-me[snippets="http-request,http-response"]
====

=== 유저 관심 프로젝트 리스트 조회 (GET /users/favorites/projects)
====
operation::user-controller-test/get-user-favorite-projects[snippets="http-request,http-response,response-fields"]
====

=== 유저 관심 대담영상 리스트 조회 (GET /users/favorites/talks)
====
operation::user-controller-test/get-user-favorite-talks[snippets="http-request,http-response,response-fields"]
====

=== 유저 관심 잡페어인터뷰영상 리스트 조회 (GET /users/favorites/jobInterviews)
====
operation::user-controller-test/get-user-favorite-interviews[snippets="http-request,http-response,response-fields"]
====

=== 유저 문의 리스트 조회 (GET /users/inquiries)
====
operation::user-controller-test/get-user-inquiries[snippets="http-request,http-response,response-fields"]
====

=== 유저 과제 제안 리스트 조회 (GET /users/proposals)
====
operation::user-controller-test/get-user-proposals[snippets="http-request,http-response,response-fields"]
====
