name: 🚀 New Feature Request
description: Propose new feature to S-TOP backend
title: "🚀 [FEAT] "
labels: ['🚀 Feature']
body:
  - type: textarea
    attributes:
      label: ❓ Describe Existing Problem
      id: feature-problem
      description: |
        해결하려는 문제를 자세히 설명해주세요!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ Describe Solution
      id: feature-solution
      description: |
        위의 문제를 해결하기 위해 어떤 기능을 추가하고 싶은 지 설명해주세요!
      value: |
        - [ ] task 1
        - [ ] task 2
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📍 More
      id: feature-more
      description: |
        기타 참고할만한 사항들을 작성해주세요!
  - type: checkboxes
    id: feature-checkboxes
    attributes:
      label: CheckList ✔️
      description: |
        Issue 올리기 전에 한 번 확인해주세요! 👍
      options:
        - label: 관련 Issue 가 이미 존재하는 지 확인해보셨나요?
          required: true
        - label: Assignees 설정
        - label: Labels 설정